# ここでワークフローのトリガーを定義
on:
  push:
    branches:
      - main  # main ブランチに push されたときに実行される

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy mycloudrun-app \
          --image gcr.io/$GCP_PROJECT_ID/mycloudrun-app \
          --region us-central1 \
          --allow-unauthenticated
